import requests
from typing import Dict
from config import config

class TelegramNotifier:
    """
    Enhanced Telegram Notifier with Exit Alerts
    """

    @staticmethod
    def _escape_markdown(text: str) -> str:
        """Escape special characters for Telegram MarkdownV2"""
        special_chars = ['_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!']
        for char in special_chars:
            text = text.replace(char, f'\\{char}')
        return text

    @staticmethod
    def send_signal(signal: Dict):
        """Send trading signal to Telegram"""

        direction_emoji = "🟢" if signal['direction'] == "LONG" else "🔴"
        fire_emoji = "🔥" if signal['score'] >= 80 else "⚡"

        pair = TelegramNotifier._escape_markdown(signal['pair'])
        direction = signal['direction']
        score = signal['score']
        leverage = signal['leverage']
        entry = TelegramNotifier._escape_markdown(f"{signal['entry']:,.2f}")
        sl = TelegramNotifier._escape_markdown(f"{signal['sl']:,.2f}")
        tp1 = TelegramNotifier._escape_markdown(f"{signal['tp1']:,.2f}")
        tp2 = TelegramNotifier._escape_markdown(f"{signal['tp2']:,.2f}")
        rsi = TelegramNotifier._escape_markdown(str(signal['rsi']))
        adx = TelegramNotifier._escape_markdown(str(signal['adx']))
        mtf = TelegramNotifier._escape_markdown(signal['mtf_trend'])
        volume = TelegramNotifier._escape_markdown(f"{signal['volume_surge']}x")
        mode = TelegramNotifier._escape_markdown(signal.get('mode', 'UNKNOWN'))
        timeframe = TelegramNotifier._escape_markdown(signal.get('timeframe', 'N/A'))
        timestamp = TelegramNotifier._escape_markdown(signal['timestamp'])

        message = f"""
{fire_emoji} *{direction} SIGNAL* {direction_emoji}

━━━━━━━━━━━━━━━━━━━━
*📊 PAIR:* `{pair}`
*💯 SCORE:* {score}/100
*⏱️ TIMEFRAME:* {timeframe}
*📈 LEVERAGE:* {leverage}x

━━━━━━━━━━━━━━━━━━━━
*🎯 ENTRY:* ₹{entry}
*🛑 STOP LOSS:* ₹{sl}
*✅ TP1:* ₹{tp1}
*✅ TP2:* ₹{tp2}

━━━━━━━━━━━━━━━━━━━━
*📉 RSI:* {rsi}
*📊 ADX:* {adx}
*🔄 MTF:* {mtf}
*📦 Volume:* {volume}

━━━━━━━━━━━━━━━━━━━━
*⚙️ MODE:* {mode}
*⏰ TIME:* {timestamp}

━━━━━━━━━━━━━━━━━━━━
_Auto\\-generated by ARUN Bot 🤖_
"""

        TelegramNotifier._send_message(message.strip(), parse_mode='MarkdownV2')

    @staticmethod
    def send_exit_alert(pair: str, reason: str, booking_pct: int, 
                       profit_pct: float = None, exit_price: float = None):
        """
        ✅ NEW: Send exit notification
        """
        
        pair_esc = TelegramNotifier._escape_markdown(pair)
        reason_esc = TelegramNotifier._escape_markdown(reason)
        booking_esc = TelegramNotifier._escape_markdown(f"{booking_pct}%")
        
        emoji = "💰" if profit_pct and profit_pct > 0 else "🛑"
        
        message = f"{emoji} *EXIT SIGNAL*\n\n"
        message += f"*📊 PAIR:* `{pair_esc}`\n"
        message += f"*📤 BOOKING:* {booking_esc}\n"
        message += f"*💡 REASON:* {reason_esc}\n"
        
        if profit_pct is not None:
            profit_esc = TelegramNotifier._escape_markdown(f"{profit_pct:+.2f}%")
            message += f"*📈 PROFIT:* {profit_esc}\n"
        
        if exit_price is not None:
            price_esc = TelegramNotifier._escape_markdown(f"{exit_price:,.2f}")
            message += f"*💵 EXIT PRICE:* ₹{price_esc}\n"
        
        message += "\n_Bot monitoring continues 🤖_"
        
        TelegramNotifier._send_message(message.strip(), parse_mode='MarkdownV2')

    @staticmethod
    def send_trailing_update(pair: str, new_sl: float, message: str):
        """
        ✅ NEW: Send trailing stop update
        """
        
        pair_esc = TelegramNotifier._escape_markdown(pair)
        sl_esc = TelegramNotifier._escape_markdown(f"{new_sl:,.6f}")
        msg_esc = TelegramNotifier._escape_markdown(message)
        
        notification = f"""
🔄 *TRAILING STOP UPDATE*

*📊 PAIR:* `{pair_esc}`
*🛑 NEW SL:* ₹{sl_esc}
*💡 STATUS:* {msg_esc}

_Profit protected 🛡️_
"""
        
        TelegramNotifier._send_message(notification.strip(), parse_mode='MarkdownV2')

    @staticmethod
    def send_daily_report(stats: Dict):
        """
        ✅ NEW: Enhanced daily report with performance metrics
        """
        
        pnl = stats.get('daily_pnl', 0)
        pnl_pct = stats.get('daily_pnl_pct', 0)
        positions = stats.get('positions_today', 0)
        wins = stats.get('wins', 0)
        losses = stats.get('losses', 0)
        win_rate = stats.get('win_rate', 0)
        
        pnl_esc = TelegramNotifier._escape_markdown(f"{pnl:+,.2f}")
        pnl_pct_esc = TelegramNotifier._escape_markdown(f"{pnl_pct:+.2f}%")
        pos_esc = TelegramNotifier._escape_markdown(str(positions))
        wins_esc = TelegramNotifier._escape_markdown(str(wins))
        losses_esc = TelegramNotifier._escape_markdown(str(losses))
        wr_esc = TelegramNotifier._escape_markdown(f"{win_rate:.1f}%")
        
        emoji = "🎉" if pnl > 0 else ("⚠️" if pnl < 0 else "💤")
        
        message = f"""
{emoji} *DAILY PERFORMANCE REPORT* {emoji}

━━━━━━━━━━━━━━━━━━━━
*💰 P&L:* ₹{pnl_esc} \\({pnl_pct_esc}\\)
*📊 Positions:* {pos_esc}
*✅ Wins:* {wins_esc}
*❌ Losses:* {losses_esc}
*📈 Win Rate:* {wr_esc}

━━━━━━━━━━━━━━━━━━━━
See you tomorrow\\! 🌙
"""
        
        TelegramNotifier._send_message(message.strip(), parse_mode='MarkdownV2')

    @staticmethod
    def send_risk_alert(alert_type: str, message: str):
        """
        ✅ NEW: Send risk management alerts
        """
        
        type_esc = TelegramNotifier._escape_markdown(alert_type)
        msg_esc = TelegramNotifier._escape_markdown(message)
        
        alert = f"""
🚨 *RISK ALERT* 🚨

*Type:* {type_esc}
*Message:* {msg_esc}

_Bot action taken 🛡️_
"""
        
        TelegramNotifier._send_message(alert.strip(), parse_mode='MarkdownV2')

    @staticmethod
    def send_chart(chart_path: str):
        """Send chart image to Telegram"""
        if not chart_path or not config.TELEGRAM_BOT_TOKEN or not config.TELEGRAM_CHAT_ID:
            return

        url = f"https://api.telegram.org/bot{config.TELEGRAM_BOT_TOKEN}/sendPhoto"

        try:
            with open(chart_path, 'rb') as photo:
                files = {'photo': photo}
                data = {'chat_id': config.TELEGRAM_CHAT_ID}

                response = requests.post(url, data=data, files=files, timeout=30)
                response.raise_for_status()
                print("✅ Chart sent to Telegram")

        except Exception as e:
            print(f"❌ Chart send failed: {e}")

    @staticmethod
    def send_explanation(explanation: str):
        """Send educational explanation to Telegram"""
        if not explanation:
            return

        escaped_explanation = TelegramNotifier._escape_markdown(explanation)
        TelegramNotifier._send_message(escaped_explanation, parse_mode='MarkdownV2')

    @staticmethod
    def send_alert(title: str, message: str):
        """Send alert message"""

        title_escaped = TelegramNotifier._escape_markdown(title)
        message_escaped = TelegramNotifier._escape_markdown(message)

        text = f"""
⚠️ *{title_escaped}* ⚠️

{message_escaped}
"""

        TelegramNotifier._send_message(text.strip(), parse_mode='MarkdownV2')

    @staticmethod
    def send_startup_message():
        """Send bot startup notification"""

        mode_display = ', '.join(config.ACTIVE_MODES) if config.MULTI_MODE_ENABLED else config.MODE
        auto_trade = '✅ ON' if config.AUTO_TRADE else '❌ OFF'
        pairs_list = ', '.join(config.PAIRS)

        mode_escaped = TelegramNotifier._escape_markdown(mode_display)
        auto_trade_escaped = TelegramNotifier._escape_markdown(auto_trade)
        max_signals = TelegramNotifier._escape_markdown(str(config.MAX_SIGNALS_PER_DAY))
        pairs_count = TelegramNotifier._escape_markdown(str(len(config.PAIRS)))
        pairs_escaped = TelegramNotifier._escape_markdown(pairs_list)

        message = f"""
🚀 *ARUN BOT STARTED* 🚀

━━━━━━━━━━━━━━━━━━━━
*⚙️ Configuration:*
• Mode: {mode_escaped}
• Auto Trade: {auto_trade_escaped}
• Max Signals: {max_signals}/day
• Pairs: {pairs_count}

━━━━━━━━━━━━━━━━━━━━
*📊 Trading Pairs:*
{pairs_escaped}

━━━━━━━━━━━━━━━━━━━━
Bot is now monitoring markets 👀
"""

        TelegramNotifier._send_message(message.strip(), parse_mode='MarkdownV2')

    @staticmethod
    def send_daily_summary(stats: Dict):
        """Send daily summary (legacy - use send_daily_report instead)"""

        mode_display = stats.get('mode', 'N/A')
        signals_today = stats.get('signals_today', 0)
        success_rate = stats.get('success_rate', 'N/A')

        mode_escaped = TelegramNotifier._escape_markdown(str(mode_display))
        signals_escaped = TelegramNotifier._escape_markdown(str(signals_today))
        success_escaped = TelegramNotifier._escape_markdown(str(success_rate))

        breakdown = ""
        if 'mode_breakdown' in stats:
            breakdown = "\n*Breakdown:*\n"
            for mode, count in stats['mode_breakdown'].items():
                mode_esc = TelegramNotifier._escape_markdown(mode)
                count_esc = TelegramNotifier._escape_markdown(str(count))
                breakdown += f"• {mode_esc}: {count_esc}\n"

        message = f"""
📊 *DAILY SUMMARY* 📊

━━━━━━━━━━━━━━━━━━━━
*Signals Generated:* {signals_escaped}
*Mode:* {mode_escaped}
*Success Rate:* {success_escaped}
{breakdown}━━━━━━━━━━━━━━━━━━━━
See you tomorrow\\! 🌙
"""

        TelegramNotifier._send_message(message.strip(), parse_mode='MarkdownV2')

    @staticmethod
    def _send_message(text: str, parse_mode: str = 'MarkdownV2'):
        """Send message to Telegram"""

        if not config.TELEGRAM_BOT_TOKEN or not config.TELEGRAM_CHAT_ID:
            print("⚠️ Telegram credentials not configured")
            print(f"Message: {text}")
            return

        url = f"https://api.telegram.org/bot{config.TELEGRAM_BOT_TOKEN}/sendMessage"

        data = {
            'chat_id': config.TELEGRAM_CHAT_ID,
            'text': text,
            'parse_mode': parse_mode
        }

        try:
            response = requests.post(url, data=data, timeout=10)
            response.raise_for_status()
            print("✅ Telegram message sent")

        except requests.exceptions.RequestException as e:
            print(f"❌ Telegram send failed: {e}")
            if hasattr(e, 'response') and e.response is not None:
                print(f"   Response: {e.response.text}")

    @staticmethod
    def test_connection():
        """Test Telegram bot connection"""

        try:
            url = f"https://api.telegram.org/bot{config.TELEGRAM_BOT_TOKEN}/getMe"
            response = requests.get(url, timeout=5)
            response.raise_for_status()

            bot_info = response.json()
            if bot_info['ok']:
                print(f"✅ Telegram bot connected: @{bot_info['result']['username']}")
                return True
            else:
                print("❌ Telegram bot connection failed")
                return False

        except requests.exceptions.RequestException as e:
            print(f"❌ Telegram test failed: {e}")
            return False