import requests
from typing import Dict
from config import config

class TelegramNotifier:
    """
    Sends premium formatted trading signals to Telegram
    """

    @staticmethod
    def _escape_markdown(text: str) -> str:
        """
        Escape special characters for Telegram MarkdownV2
        Must escape: _ * [ ] ( ) ~ ` > # + - = | { } . !
        """
        special_chars = ['_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!']
        for char in special_chars:
            text = text.replace(char, f'\\{char}')
        return text

    @staticmethod
    def send_signal(signal: Dict):
        """
        Send trading signal to Telegram channel/group
        """

        direction_emoji = "🟢" if signal['direction'] == "LONG" else "🔴"
        fire_emoji = "🔥" if signal['score'] >= 80 else "⚡"
        
        # Get values
        pair = signal['pair']
        direction = signal['direction']
        score = signal['score']
        leverage = signal['leverage']
        entry = signal['entry']
        sl = signal['sl']
        tp1 = signal['tp1']
        tp2 = signal['tp2']
        rsi = signal['rsi']
        adx = signal['adx']
        mtf = signal['mtf_trend']
        volume = signal['volume_surge']
        mode = signal.get('mode', 'UNKNOWN')
        timeframe = signal.get('timeframe', 'N/A')
        timestamp = signal['timestamp']

        # Build message with proper escaping
        message = f"""
{fire_emoji} *{direction} SIGNAL* {direction_emoji}

━━━━━━━━━━━━━━━━━━━━
*📊 PAIR:* `{pair}`
*💯 SCORE:* {score}/100
*⏱️ TIMEFRAME:* {timeframe}
*📈 LEVERAGE:* {leverage}x

━━━━━━━━━━━━━━━━━━━━
*🎯 ENTRY:* ₹{entry:,.2f}
*🛑 STOP LOSS:* ₹{sl:,.2f}
*✅ TP1:* ₹{tp1:,.2f}
*✅ TP2:* ₹{tp2:,.2f}

━━━━━━━━━━━━━━━━━━━━
*📉 RSI:* {rsi}
*📊 ADX:* {adx}
*🔄 MTF:* {mtf}
*📦 Volume:* {volume}x

━━━━━━━━━━━━━━━━━━━━
*⚙️ MODE:* {mode}
*⏰ TIME:* {timestamp}

━━━━━━━━━━━━━━━━━━━━
_Auto\\-generated by ARUN Bot 🤖_
        """

        # Escape the entire message
        escaped_message = TelegramNotifier._escape_markdown(message.strip())

        TelegramNotifier._send_message(escaped_message, parse_mode='MarkdownV2')

    @staticmethod
    def send_alert(title: str, message: str):
        """Send alert message"""
        
        text = f"""
⚠️ *{title}* ⚠️

{message}
        """
        
        escaped_text = TelegramNotifier._escape_markdown(text.strip())
        TelegramNotifier._send_message(escaped_text, parse_mode='MarkdownV2')

    @staticmethod
    def send_startup_message():
        """Send bot startup notification"""
        
        mode_display = ', '.join(config.ACTIVE_MODES) if config.MULTI_MODE_ENABLED else config.MODE
        auto_trade = '✅ ON' if config.AUTO_TRADE else '❌ OFF'
        pairs_list = ', '.join(config.PAIRS)

        message = f"""
🚀 *ARUN BOT STARTED* 🚀

━━━━━━━━━━━━━━━━━━━━
*⚙️ Configuration:*
• Mode: {mode_display}
• Auto Trade: {auto_trade}
• Max Signals: {config.MAX_SIGNALS_PER_DAY}/day
• Pairs: {len(config.PAIRS)}

━━━━━━━━━━━━━━━━━━━━
*📊 Trading Pairs:*
{pairs_list}

━━━━━━━━━━━━━━━━━━━━
Bot is now monitoring markets 👀
        """

        escaped_message = TelegramNotifier._escape_markdown(message.strip())
        TelegramNotifier._send_message(escaped_message, parse_mode='MarkdownV2')

    @staticmethod
    def send_daily_summary(stats: Dict):
        """Send daily summary"""
        
        mode_display = stats.get('mode', 'N/A')
        signals_today = stats.get('signals_today', 0)
        success_rate = stats.get('success_rate', 'N/A')
        
        # Mode breakdown if available
        breakdown = ""
        if 'mode_breakdown' in stats:
            breakdown = "\n*Breakdown:*\n"
            for mode, count in stats['mode_breakdown'].items():
                breakdown += f"• {mode}: {count}\n"

        message = f"""
📊 *DAILY SUMMARY* 📊

━━━━━━━━━━━━━━━━━━━━
*Signals Generated:* {signals_today}
*Mode:* {mode_display}
*Success Rate:* {success_rate}
{breakdown}
━━━━━━━━━━━━━━━━━━━━
See you tomorrow! 🌙
        """

        escaped_message = TelegramNotifier._escape_markdown(message.strip())
        TelegramNotifier._send_message(escaped_message, parse_mode='MarkdownV2')

    @staticmethod
    def _send_message(text: str, parse_mode: str = 'MarkdownV2'):
        """
        Send message to Telegram
        """

        if not config.TELEGRAM_BOT_TOKEN or not config.TELEGRAM_CHAT_ID:
            print("⚠️ Telegram credentials not configured")
            print(f"Message: {text}")
            return

        url = f"https://api.telegram.org/bot{config.TELEGRAM_BOT_TOKEN}/sendMessage"

        data = {
            'chat_id': config.TELEGRAM_CHAT_ID,
            'text': text,
            'parse_mode': parse_mode
        }

        try:
            response = requests.post(url, data=data, timeout=10)
            response.raise_for_status()
            print("✅ Telegram message sent")

        except requests.exceptions.RequestException as e:
            print(f"❌ Telegram send failed: {e}")
            # Print response for debugging
            if hasattr(e, 'response') and e.response is not None:
                print(f"   Response: {e.response.text}")

    @staticmethod
    def test_connection():
        """Test Telegram bot connection"""
        
        try:
            url = f"https://api.telegram.org/bot{config.TELEGRAM_BOT_TOKEN}/getMe"
            response = requests.get(url, timeout=5)
            response.raise_for_status()

            bot_info = response.json()
            if bot_info['ok']:
                print(f"✅ Telegram bot connected: @{bot_info['result']['username']}")
                return True
            else:
                print("❌ Telegram bot connection failed")
                return False

        except requests.exceptions.RequestException as e:
            print(f"❌ Telegram test failed: {e}")
            return False